
import Anish from '../public/anish.png';
import Faizan from '../public/faizan.png';
import Kushal from '../public/kushal.png';
import Priyo from '../public/priyobrata.png';
import Arghya from '../public/arghya.png';
import Debanjan from '../public/debanjan.png';
import Bhaskar from '../public/bhaskar.png';
import Aniruddha from '../public/aniruddha.png';
import Blank from '../public/blank.jpeg';
import Susmita from '../public/susmita.png';
import Indronil from '../public/Indronil.png';
import Debolina from '../public/debolina.png';
import Saptarshi from '../public/saptarshi.png';
import Avisek from '../public/Avisek.png';
import Shounak from '../public/shounak.png';
import Abhishek from '../public/abhishek.png';
import Sankha from '../public/sankha.png';
import Swagatam from '../public/swagatam.jpg';
import Arka from '../public/Arka.jpeg';
import Shinjon from '../public/shinjon.jpeg';
import Sandipan from '../public/sandipan.png';
import Arkajyoti from '../public/arkajyoti.jpg';
import Imon from '../public/imon.jpeg';
import Sayantan from '../public/sayantan.jpeg';
import Srinjoy from '../public/srinjoy.jpg';
import Anal from '../public/anal.jpeg';
import Arkaprabha from '../public/arkaprabha.jpeg';
import { CgProfile } from "react-icons/cg";


export interface TeamMember {
  id: string;
  name: string;
  role: 'professor' | 'jrf' | 'srf' | 'alumni' | 'adjunct';
  title: string;
  remark?: string;
  image?: any;
  researchAreas: string[];
  joiningDate: string;
  paperCount?: number;
  dblpName?: string;
  biasCount?: number;
  citations?: string;
  website?: string;
  email?: string;
  linkedin?: string;
  github?: string;
  scholar?: string;
  bio?: string;
}

export const teamMembers: TeamMember[] = [
  {
    id: '1',
    name: 'Dr. Swagatam Das',
    role: 'professor',
    title: 'Principal Investigator & Lab Supervisor',
    image: Swagatam,
    researchAreas: ['Artificial Intelligence', 'Metaheuristics', 'Differential Evolution', 'Swarm Intelligence', 'Machine Learning'],
    joiningDate: '2011-08-01',
    paperCount: 604,
    dblpName: 'Swagatam_Das',
    biasCount: 200,
    citations: '35k',
    website: 'http://web.isical.ac.in/~swagatam.das/',
    email: 'swagatam.das@isical.ac.in',
    scholar: 'https://scholar.google.co.in/citations?hl=en&user=L8XYpAwAAAAJ&view_op=list_works&sortby=pubdate',
    bio: ' Professor-in-Charge (2024 – 26) Computer and Communication Sciences Division, ISI ',
  },
  {
    id: '2',
    name: 'Anish Chakrabarty',
    role: 'srf',
    title: 'SMU, PhD-Stat',
    remark: "Thesis Submitted",
    image: Anish,
    researchAreas: ['Deep Learning', 'High-dimensional Statistics'],
    joiningDate: '2019-01-15',
    paperCount: 10,
    dblpName: 'Anish_Chakrabarty',
    biasCount: 0,
    website: 'https://chakrabartyanish.faculty.bio/',
    scholar: 'https://scholar.google.com/citations?hl=en&user=KfCQY5oAAAAJ&view_op=list_works&sortby=pubdate',
    email: 'chakrabarty.anish@gmail.com?subject=[FromMLRGSite]',
    bio: 'Loading...',
  },
  {
    id: '3',
    name: 'Faizanuddin Ansari',
    role: 'srf',
    title: 'ECSU, PhD-CS',
    remark: "Thesis Submitted",
    image: Faizan,
    researchAreas: ['Long Tailed Imbalance', 'Meta Learning', 'AI for Health', 'Fairness', 'LLM'],
    joiningDate: '2019-09-01',
    paperCount: 7,
    dblpName: 'Faizanuddin_Ansari',
    biasCount: 2,
    email: 'faizanuddin_r@isical.ac.in?subject=[FromMLRGSite]',
    website: 'https://web.isical.ac.in/~faizanuddin_r/',
    github: 'https://github.com/ziaf/',
    linkedin: 'https://in.linkedin.com/in/faizanuddinansari',
    scholar: 'https://orcid.org/0009-0009-5517-8846',
    bio: "Most real-world datasets are far from ideal—they're imbalanced, biased, or simply too small to learn from effectively — and that's exactly where he comes in.",
  },
  {
    id: '4',
    name: 'Kushal Bose',
    role: 'srf',
    title: 'ECSU, PhD-CS',
    remark: "Thesis Submitted",
    image: Kushal,
    researchAreas: ['Geometric Deep Learning','Non-Euclidean Spaces'],
    joiningDate: '2019-01-10',
    paperCount: 9,
    dblpName: 'Kushal_Bose',
    biasCount: 0,
    website: 'https://kushalbose92.github.io',
    scholar: 'https://scholar.google.co.in/citations?hl=en&user=CifdghYAAAAJ&view_op=list_works&sortby=pubdate',
    linkedin: 'https://in.linkedin.com/in/kushal-bose-5405aa128',
    // instagram: 'https://www.instagram.com/kushalbose92/',
    bio: 'Loading...',
  },
  {
    id: '5',
    name: 'Indranil Ojha',
    role: 'srf',
    title: 'ECSU, PhD-CS',
    image: Indronil,
    researchAreas: ['Machine Learning'],
    joiningDate: '2019-01-10',
    paperCount: 2,
    dblpName: 'Indranil_Ojha',
    biasCount: 0,
    scholar: 'https://scholar.google.com/citations?hl=en&user=TwUA3XIAAAAJ&view_op=list_works&sortby=pubdate',
    linkedin: 'https://in.linkedin.com/in/indranil-ojha-9934282',
    bio: 'Loading...',
  },
  {
    id: '6',
    name: 'Priyobrata Mondal',
    role: 'srf',
    title: 'ECSU, PhD-CS',
    image: Priyo,
    researchAreas: ['Imbalance', 'LongTailed Imbalance', 'Data Irregularity',  'Generative Modeling'],
    joiningDate: '2020-01-10',
    paperCount: 3,
    dblpName: 'Priyobrata_Mondal',
    biasCount: 3,
    scholar: 'https://scholar.google.com/citations?hl=en&user=6SgZZG4AAAAJ&view_op=list_works&sortby=pubdate',
    email: 'priyobrata.mondal10@gmail.com?subject=[FromMLRGSite]',
    bio: 'Loading...',
  },
  {
    id: '7',
    name: 'Srinjoy Roy',
    role: 'srf',
    title: 'IAI, PhD-CS',
    image: Srinjoy,
    researchAreas: ['Reinforcement Learning'],
    paperCount: 2,
    dblpName: 'Srinjoy_Roy',
    biasCount: 2,
    joiningDate: '2020-01-10',
    linkedin: 'https://in.linkedin.com/in/srinjoy-roy-6846341a6',
    email: 'srinjoyroyonline@gmail.com ?subject=[FromMLRGSite]',
    bio: 'His research interests include reinforcement learning, general intelligence, and the explainability of reinforcement learning algorithms.',
  },
  {
    id: '8',
    name: 'Arghya Pratihar',
    role: 'srf',
    title: 'ECSU, PhD-CS',
    image: Arghya,
    researchAreas: ['Topological Deep Learning', 'Non-Euclidean Spaces'],
    joiningDate: '2022-01-10',
    paperCount: 2,
    dblpName: 'Arghya_Pratihar',
    biasCount: 3,
    linkedin: 'https://in.linkedin.com/in/arghya-pratihar-contactarghya',
    email: 'arghya.pratihar_r@isical.ac.in?subject=[FromMLRGSite]',
    bio: 'Loading...',
  },
  {
    id: '9',
    name: 'Aniruddha Mandal',
    role: 'jrf',
    title: 'ECSU, PhD-CS',
    image: Aniruddha,
    researchAreas: ['Graph Neural Network'],
    paperCount: 3,
    dblpName: 'Aniruddha_Mandal',
    biasCount: 0,
    joiningDate: '2023-01-10',
    linkedin: 'https://in.linkedin.com/in/aniruddha-mandal-16061a103',
    bio: 'Loading...',
  },
  {
    id: '10',
    name: 'Bhaskar Pramanik',
    role: 'jrf',
    title: 'ECSU, PhD-CS',
    image: Bhaskar,
    researchAreas: ['Graph Neural Network'],
    paperCount: 3,
    dblpName: 'Bhaskar_Pramanik',
    biasCount: 0,
    joiningDate: '2023-01-10',
    linkedin: 'https://in.linkedin.com/in/bhaskar-pramanik-291904162',
    bio: 'Loading...',
  },
  {
    id: '11',
    name: 'Debanjan Dutta',
    role: 'jrf',
    image: Debanjan,
    title: 'ECSU, PhD-CS',
    researchAreas: ['Language Models', 'Formal Languages', 'Expressiveness'],
    joiningDate: '2023-01-10',
    paperCount: 2,
    dblpName: 'Debanjan_Dutta',
    biasCount: 0,
    website: 'https://web.isical.ac.in/~debanjandutta_r',
    email: 'debanjandutta_r@isical.ac.in?subject=[FromMLRGSite]',
    bio: 'Works on investigating the expressive power of Language Models from the lens of theoretical computer science.',
  },
  {
    id: '12',
    name: 'Shinjon Chakraborty',
    role: 'jrf',
    title: 'SMU, PhD-Stat',
    image: Shinjon,
    researchAreas: ['Causal Inference', 'Optimal Transport'],
    joiningDate: '2023-01-10',
    paperCount: 4,
    dblpName: 'Shinjon_Chakraborty',
    biasCount: 0,
    scholar: 'https://www.researchgate.net/profile/Shinjon_Chakraborty',
    linkedin: 'https://in.linkedin.com/in/shinjon-chakraborty-a684b4209',
    email: 'shinjonchakraborty07@gmail.com?subject=[FromMLRGSite]',
    bio: 'Currently on the path of exploring Causal Inference and Statistical Learning theory. He is also an enthusiast in Theoretical Statistics, and Asymptotic Inference.',
  },
  {
    id: '13',
    name: 'Pritam Mukherjee',
    role: 'jrf',
    title: 'ECSU, PhD-CS',
    researchAreas: ['Graph Learning'],
    joiningDate: '2024-01-10',
    paperCount: 4,
    dblpName: 'Pritam_Mukherjee',
    biasCount: 0,
    bio: 'Loading....',
  },
  {
    id: '14',
    name: 'Dr. Susmita Ghosh',
    role: 'alumni',
    title: 'Data Scientist @ ThreeV Technologies, Inc.',
    image: Susmita,
    researchAreas: ['Machine Learning', 'Deep Learning', 'EEG'],
    joiningDate: '2018-03-01',
    paperCount: 7,
    dblpName: 'Susmita_Ghosh',
    biasCount: 0,
    scholar: 'https://scholar.google.co.in/citations?hl=en&user=7yt-PN4AAAAJ&view_op=list_works&sortby=pubdate',
    linkedin: 'https://in.linkedin.com/in/susmita-ghosh-5223b8a1',
  },
  {
    id: '15',
    name: 'Dr. Sandipan Dhar',
    role: 'alumni',
    title: 'Postdoctoral Researcher @ IIT-Bombay',
    image: Sandipan,
    researchAreas: ['Deep Learning', 'Speech Synthesis', 'Speech Classification', 'Medical Imaging'],
    joiningDate: '2018-03-01',
    paperCount: 20,
    dblpName: 'Sandipan_Dhar',
    biasCount: 0,
    website: 'https://sites.google.com/view/sandipan1994',
    scholar: 'https://scholar.google.com/citations?hl=en&user=37kX7hYAAAAJ&view_op=list_works&sortby=pubdate',
    linkedin: 'https://www.linkedin.com/in/sandi94/',
    github: 'https://github.com/SandyPanda-MLDL'
  },
  {
    id: '16',
    name: 'Dr. Avisek Gupta',
    role: 'alumni',
    title: 'Assistant Professor  @ IAI, TCG-CREST',
    image: Avisek,
    researchAreas: ['Deep Learning', 'Machine Learning', 'Artifical Intelligence'],
    joiningDate: '2016-03-01',
    paperCount: 13,
    dblpName: 'Avisek_Gupta',
    biasCount: 0,
    website: 'https://avisekgupta.github.io/',
    linkedin: 'https://www.linkedin.com/in/avisek-gupta-66956b96/',
    scholar: 'https://scholar.google.co.in/citations?hl=en&user=mVhNXEWludgC&view_op=list_works&sortby=pubdate',
    github: 'https://github.com/Avisek20',
    email: 'avisek.gupta@tcgcrest.org?subject=[FromMLRGSite]'
  },
  {
    id: '17',
    name: 'Dr. Sankha Subhra Mullick',
    role: 'alumni',
    title: 'Senior AI Reseracher @ Dolby Laboratories',
    image: Sankha,
    researchAreas: ['Machine Learning', 'Class Imbalanced Learning', 'Evolutionary Optimization', 'Deep Learning'],
    joiningDate: '2016-03-01',
    paperCount: 18,
    dblpName: 'Sankha_Subhra_Mullick',
    biasCount: 0,
    website: 'https://sankhasubhra.github.io/',
    linkedin: 'https://www.linkedin.com/in/sankha-subhra-mullick-92652119',
    github: 'https://github.com/SankhaSubhra',
    scholar: 'https://scholar.google.com/citations?hl=en&user=QnzlBI8AAAAJ&view_op=list_works&sortby=pubdate',
    email: 'mullicksankhasubhra@gmail.com?subject=[FromMLRGSite]'
  },
  {
    id: '18',
    name: 'Dr. Shounak Datta',
    role: 'alumni',
    title: 'Senior Research Engineer @ ARM Inc.',
    image: Shounak,
    researchAreas: ['Machine Learning', 'Imbalanced Classification', 'Missing Data', 'Clustering', 'Optimization'],
    joiningDate: '2015-03-01',
    paperCount: 26,
    dblpName: 'Shounak_Datta',
    biasCount: 0,
    website: 'https://shounak-d.github.io/',
    linkedin: 'https://www.linkedin.com/in/shounak-datta-94782a169',
    github: 'https://github.com/Shounak-D',
    scholar: 'https://scholar.google.co.in/citations?hl=en&user=qtW4ugoAAAAJ&view_op=list_works&sortby=pubdate',
    email: 'shounak.jaduniv@gmail.com?subject=[FromMLRGSite]'
  },
  {
    id: '19',
    name: 'Dr. Abhishek Kumar',
    role: 'adjunct',
    title: 'VSB-Technical University of Ostrava',
    image: Abhishek,
    researchAreas: ['Evolutionary Computation', 'Constraint Handling Techniques', 'Power Flow Algorithms', 'Power System'],
    joiningDate: '2022-03-01',
    paperCount: 69,
    dblpName: 'Abhishek_Kumar',
    biasCount: 0,
    website: 'https://abhisheka456.github.io/',
    github: 'https://github.com/abhisheka456/',
    scholar: 'https://scholar.google.com/citations?hl=en&user=uZRyTFIAAAAJ&view_op=list_works&sortby=pubdate',
    email: 'abhishek.kumar.eee13@iitbhu.ac.in?subject=[FromMLRGSite]'
  },
  {
    id: '20',
    name: 'Anal Roy Chowdhury',
    role: 'alumni',
    title: 'PhD Scholar @ IACS',
    image: Anal,
    researchAreas: ['Multi-View Clustering', 'Machine Learning', 'Deep Learning', 'Semiconductor Nanostructure'],
    joiningDate: '2021-03-01',
    paperCount: 7,
    dblpName: 'Anal_Roy_Chowdhury',
    biasCount: 7,
    scholar: 'https://scholar.google.co.in/citations?hl=en&user=CukHpC4AAAAJ&view_op=list_works&sortby=pubdate',
    email: 'analroychowdhury084@gmail.com?subject=[FromMLRGSite]',
    linkedin: 'https://in.linkedin.com/in/anal-roy-chowdhury-00a696188',
    bio: 'Joined as PLP'
  },
  {
    id: '21',
    name: 'Arkaprabha Basu',
    role: 'alumni',
    title: 'PhD student @ UAEU',
    image: Arkaprabha,
    researchAreas: ['Multimodality', 'Large Language Model', 'Computer Vision'],
    joiningDate: '2021-03-01',
    paperCount: 11,
    dblpName: 'Arkaprabha_Basu',
    biasCount: 0,
    email: 'arkaprabha17@gmail.com?subject=[FromMLRGSite]',
    scholar: 'https://scholar.google.com/citations?hl=en&user=7S_jA3IAAAAJ&view_op=list_works&sortby=pubdate',
    website: 'https://thecoder1012.github.io/',
    github: 'https://github.com/Thecoder1012',
    bio: 'Joined as PLP'
  },
  {
    id: '22',
    name: 'Dr. Arkajyoti Saha',
    role: 'alumni',
    title: 'Assistant Professor @ UC Irvine',
    image: Arkajyoti,
    researchAreas: ['Statistics', 'Machine Learning', 'Spatial Statistics', 'Artificial Intelligence'],
    joiningDate: '2015-03-01',
    paperCount: 20,
    dblpName: 'Arkajyoti_Saha',
    biasCount: 0,
    website: 'https://www.arkajyotisaha.com/',
    email: 'arkajyos@uci.edu?subject=[FromMLRGSite]',
    bio: 'Joined as UnderGrad Student.'
  },
  {
    id: '23',
    name: 'Dr. Saptarshi Chakraborty',
    role: 'alumni',
    title: 'Assistant Professor @ University of Michigan',
    image: Saptarshi,
    researchAreas: ['Machine Learning', 'Clustering', 'Statistical Learning Theory', 'Deep Learning', 'Robust Statistics'],
    joiningDate: '2020-03-01',
    paperCount: 28,
    dblpName: 'Saptarshi_Chakraborty',
    biasCount: 0,
    website: 'https://saptarshic27.github.io',
    github: 'https://github.com/saptarshic27',
    scholar: 'https://scholar.google.com/citations?hl=en&user=BAH6owQAAAAJ&view_op=list_works&sortby=pubdate',
    email: 'saptarshic@berkeley.edu?subject=[FromMLRGSite]',
    bio: 'Joined as UnderGrad Student.'
  },
  {
    id: '24',
    name: 'Debolina Paul',
    role: 'alumni',
    title: 'DPhil @ LMH, University of oxford',
    image: Debolina,
    researchAreas: ['Machine Learning', 'Deep Learning', 'Learning Theory', 'Optimization', 'Optimal Transport'],
    joiningDate: '2020-03-01',
    paperCount: 17,
    dblpName: 'Debolina_Paul',
    biasCount: 0,
    scholar: 'https://scholar.google.co.in/citations?hl=en&user=TDakv1QAAAAJ&view_op=list_works&sortby=pubdate',
    bio: 'Joined as UnderGrad Student.'
  },
  {
    id: '25',
    name: 'Dr. Imon Banerjee',
    role: 'alumni',
    title: 'Assistant Professor @ Northwestern University',
    image: Imon,
    researchAreas: ['Applied Statistics', 'Machine Learning', 'Theoretical Statistics'],
    joiningDate: '2019-03-01',
    paperCount: 8,
    dblpName: 'Imon_Banerjee',
    biasCount: 0,
    website: 'https://ibanerj750.github.io/',
    scholar: 'https://scholar.google.com/citations?hl=en&user=9MotWmwAAAAJ&view_op=list_works&sortby=pubdate',
    // instagram: 'https://www.instagram.com/imon750/',
    bio: 'Joined as UnderGrad Student.'
  },
  {
    id: '26',
    name: 'Dr. Sayantan Kumar',
    role: 'alumni',
    title: 'Postdoctoral Fellow @ National Institures on Health',
    image: Sayantan,
    researchAreas: ['Machine Learning', 'AI in Healthcare', 'Biomedical Informatics', 'Precision Medicine'],
    joiningDate: '2019-03-01',
    paperCount: 23,
    dblpName: 'Sayantan_Kumar',
    biasCount: 0,
    email: 'kumarsayantan94@gmail.com?subject=[FromMLRGSite]',
    website: 'https://sayantankumar.github.io/',
    github: 'https://github.com/SayantanKumar',
    linkedin: 'https://www.linkedin.com/in/sayantan-kumar-14550812a',
    scholar: 'https://scholar.google.com/citations?hl=en&user=ytMVdOMAAAAJ&view_op=list_works&sortby=pubdate',
    bio: 'Joined as UnderGrad Student.'
  },
  {
    id: '27',
    name: 'Dr. Arka Ghosh',
    role: 'alumni',
    title: 'Associate Researcher @ DeustoTech',
    image: Arka,
    researchAreas: ['Evolutionary Algorithm', 'Machine Learning'],
    joiningDate: '2017-03-01',
    paperCount: 23,
    dblpName: 'Arka_Ghosh',
    biasCount: 2,
    email: 'arka.ghosh@deusto.es?subject=[FromMLRGSite]',
    scholar: 'https://scholar.google.co.in/citations?hl=en&user=dOR684AAAAAJ&view_op=list_works&sortby=pubdate',
    website: 'https://deustotech.deusto.es/en/member/ghosh-arka/',
    linkedin: 'https://www.linkedin.com/in/sayantan-kumar-14550812a',
    bio: 'Joined as UnderGrad Student.'
  },
];
